"""add_early_access_table

Revision ID: 6fee2c7e3774
Revises: 7783f41b4762
Create Date: 2026-02-16 14:50:29.443381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fee2c7e3774'
down_revision = '7783f41b4762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('early_access',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('age_range', sa.String(length=50), nullable=False),
    sa.Column('professional_profiles', sa.JSON(), nullable=False),
    sa.Column('professional_profiles_other', sa.Text(), nullable=True),
    sa.Column('current_situation', sa.String(length=255), nullable=False),
    sa.Column('current_situation_other', sa.Text(), nullable=True),
    sa.Column('programming_experience', sa.String(length=255), nullable=False),
    sa.Column('platforms_used', sa.JSON(), nullable=False),
    sa.Column('platforms_used_other', sa.Text(), nullable=True),
    sa.Column('biggest_frustrations', sa.JSON(), nullable=False),
    sa.Column('biggest_frustrations_other', sa.Text(), nullable=True),
    sa.Column('abandoned_courses', sa.String(length=255), nullable=False),
    sa.Column('project_types', sa.JSON(), nullable=False),
    sa.Column('project_types_other', sa.Text(), nullable=True),
    sa.Column('deployment_importance', sa.String(length=255), nullable=False),
    sa.Column('feature_ranking', sa.JSON(), nullable=False),
    sa.Column('weekly_time', sa.String(length=50), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('monthly_payment', sa.String(length=100), nullable=False),
    sa.Column('confirmations', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONTACTED', 'APPROVED', 'REJECTED', name='earlyaccessstatus'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_early_access_email'), 'early_access', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_early_access_email'), table_name='early_access')
    op.drop_table('early_access')
    sa.Enum('PENDING', 'CONTACTED', 'APPROVED', 'REJECTED', name='earlyaccessstatus').drop(op.get_bind())
    # ### end Alembic commands ###
